/**
 * words-band1.js
 * 
 * Comprehensive core vocabulary dataset for the ditza-noy/vocab-flow-pwa application.
 * Contains the Ministry of Education Band 1 foundation level words with Hebrew translations.
 */

const band1Words = [
  // --- A ---
  { english: "a / an", hebrew: "תווית המיידעת שם עצם (יחיד)" },
  { english: "able", hebrew: "יכול, מסוגל" },
  { english: "about", hebrew: "על, אודות, בערך" },
  { english: "above", hebrew: "מעל" },
  { english: "accident", hebrew: "תאונה" },
  { english: "across", hebrew: "מעבר ל, מצד לצד" },
  { english: "act", hebrew: "לפעול, להתנהג" },
  { english: "action", hebrew: "פעולה" },
  { english: "activity", hebrew: "פעילות" },
  { english: "actor", hebrew: "שחקן" },
  { english: "add", hebrew: "להוסיף" },
  { english: "address", hebrew: "כתובת" },
  { english: "adult", hebrew: "מבוגר" },
  { english: "afraid", hebrew: "מפחד" },
  { english: "after", hebrew: "אחרי" },
  { english: "afternoon", hebrew: "אחר הצהריים" },
  { english: "again", hebrew: "שוב" },
  { english: "age", hebrew: "גיל" },
  { english: "ago", hebrew: "לפני (זמן)" },
  { english: "agree", hebrew: "להסכים" },
  { english: "air", hebrew: "אוויר" },
  { english: "airplane", hebrew: "מטוס" },
  { english: "all", hebrew: "הכל, כל" },
  { english: "almost", hebrew: "כמעט" },
  { english: "alone", hebrew: "לבד" },
  { english: "along", hebrew: "לאורך" },
  { english: "already", hebrew: "כבר" },
  { english: "also", hebrew: "גם" },
  { english: "always", hebrew: "תמיד" },
  { english: "am / I'm", hebrew: "אני / אני נמצא (פועל עזר)" },
  { english: "among", hebrew: "בין (מתוך קבוצה)" },
  { english: "and", hebrew: "ו... (חיבור)" },
  { english: "angry", hebrew: "כועס" },
  { english: "animal", hebrew: "חיה" },
  { english: "another", hebrew: "אחר, עוד אחד" },
  { english: "answer", hebrew: "תשובה, לענות" },
  { english: "any", hebrew: "כלשהו, אף אחד" },
  { english: "anyone", hebrew: "מישהו, כל אחד" },
  { english: "anything", hebrew: "משהו, כל דבר" },
  { english: "appear", hebrew: "להופיע" },
  { english: "apple", hebrew: "תפוח" },
  { english: "are", hebrew: "הם/אנחנו/אתם (פועל עזר)" },
  { english: "area", hebrew: "אזור" },
  { english: "arm", hebrew: "זרוע" },
  { english: "around", hebrew: "מסביב" },
  { english: "arrive", hebrew: "להגיע" },
  { english: "art", hebrew: "אמנות" },
  { english: "as", hebrew: "כמו, כאשר" },
  { english: "ask", hebrew: "לשאול, לבקש" },
  { english: "at", hebrew: "ב..." },
  { english: "at home", hebrew: "בבית" },
  { english: "aunt", hebrew: "דודה" },
  { english: "autumn", hebrew: "סתיו" },
  { english: "away", hebrew: "הרחק" },

  // --- B ---
  { english: "baby", hebrew: "תינוק" },
  { english: "back", hebrew: "גב, אחורה, חזרה" },
  { english: "bad", hebrew: "רע" },
  { english: "bag", hebrew: "תיק, שקית" },
  { english: "bake", hebrew: "לאפות" },
  { english: "ball", hebrew: "כדור" },
  { english: "banana", hebrew: "בננה" },
  { english: "bank", hebrew: "בנק, גדה של נהר" },
  { english: "be", hebrew: "להיות" },
  { english: "beautiful", hebrew: "יפה" },
  { english: "because", hebrew: "בגלל ש..., מפני ש..." },
  { english: "because of", hebrew: "בגלל" },
  { english: "bed", hebrew: "מיטה" },
  { english: "before", hebrew: "לפני" },
  { english: "begin", hebrew: "להתחיל" },
  { english: "behind", hebrew: "מאחורי" },
  { english: "believe", hebrew: "להאמין" },
  { english: "beside", hebrew: "על יד, לצד" },
  { english: "best", hebrew: "הכי טוב" },
  { english: "better", hebrew: "טוב יותר" },
  { english: "between", hebrew: "בין" },
  { english: "big", hebrew: "גדול" },
  { english: "birthday", hebrew: "יום הולדת" },
  { english: "black", hebrew: "שחור" },
  { english: "blue", hebrew: "כחול" },
  { english: "board", hebrew: "לוח" },
  { english: "body", hebrew: "גוף" },
  { english: "book", hebrew: "ספר" },
  { english: "bored", hebrew: "משועמם" },
  { english: "boring", hebrew: "משעמם" },
  { english: "bottle", hebrew: "בקבוק" },
  { english: "box", hebrew: "קופסה" },
  { english: "boy", hebrew: "ילד, בחור" },
  { english: "bread", hebrew: "לחם" },
  { english: "break", hebrew: "לשבור, להפסיק" },
  { english: "breakfast", hebrew: "ארוחת בוקר" },
  { english: "bring", hebrew: "להביא" },
  { english: "brother", hebrew: "אח" },
  { english: "brown", hebrew: "חום" },
  { english: "build", hebrew: "לבנות" },
  { english: "bus", hebrew: "אוטובוס" },
  { english: "busy", hebrew: "עסוק" },
  { english: "but", hebrew: "אבל" },
  { english: "buy", hebrew: "לקנות" },
  { english: "by", hebrew: "על ידי, ליד" },

  // --- C ---
  { english: "call", hebrew: "להתקשר, לקרוא ל..." },
  { english: "can", hebrew: "יכול, מסוגל" },
  { english: "capital", hebrew: "עיר בירה, אות גדולה" },
  { english: "car", hebrew: "מכונית" },
  { english: "careful", hebrew: "זהיר" },
  { english: "cat", hebrew: "חתול" },
  { english: "catch", hebrew: "לתפוס" },
  { english: "center", hebrew: "מרכז" },
  { english: "chair", hebrew: "כיסא" },
  { english: "change", hebrew: "לשנות, להחליף, עודף" },
  { english: "cheap", hebrew: "זול" },
  { english: "children", hebrew: "ילדים" },
  { english: "chocolate", hebrew: "שוקולד" },
  { english: "city", hebrew: "עיר" },
  { english: "class", hebrew: "כיתה" },
  { english: "classroom", hebrew: "חדר לימוד" },
  { english: "clean", hebrew: "נקי, לנקות" },
  { english: "clear", hebrew: "ברור, בהיר" },
  { english: "climb", hebrew: "לטפס" },
  { english: "clock", hebrew: "שעון" },
  { english: "close", hebrew: "לסגור" },
  { english: "closed", hebrew: "סגור" },
  { english: "clothes", hebrew: "בגדים" },
  { english: "coat", hebrew: "מעיל" },
  { english: "coffee", hebrew: "קפה" },
  { english: "cold", hebrew: "קר, צינון" },
  { english: "color", hebrew: "צבע" },
  { english: "come", hebrew: "לבוא" },
  { english: "come back", hebrew: "לחזור" },
  { english: "computer", hebrew: "מחשב" },
  { english: "cook", hebrew: "לבשל" },
  { english: "cool", hebrew: "קריר, מגניב" },
  { english: "copy", hebrew: "להעתיק, עותק" },
  { english: "corner", hebrew: "פינה" },
  { english: "cost", hebrew: "לעלות (מחיר), מחיר" },
  { english: "count", hebrew: "לספור" },
  { english: "country", hebrew: "מדינה, ארץ, כפר" },
  { english: "course / of course", hebrew: "קורס / כמובן" },
  { english: "cousin", hebrew: "בן/בת דוד" },
  { english: "cow", hebrew: "פרה" },
  { english: "cry", hebrew: "לבכות, לצעוק" },
  { english: "cut", hebrew: "לחתוך" },

  // --- D ---
  { english: "dad", hebrew: "אבא" },
  { english: "dance", hebrew: "לרקוד, ריקוד" },
  { english: "dangerous", hebrew: "מסוכן" },
  { english: "dark", hebrew: "חשוך, כהה" },
  { english: "date", hebrew: "תאריך, תמר" },
  { english: "daughter", hebrew: "בת" },
  { english: "day", hebrew: "יום" },
  { english: "dear", hebrew: "יקר (במכתב), חביב" },
  { english: "decide", hebrew: "להחליט" },
  { english: "deep", hebrew: "עמוק" },
  { english: "desk", hebrew: "שולחן כתיבה" },
  { english: "dictionary", hebrew: "מילון" },
  { english: "different", hebrew: "שונה" },
  { english: "difficult", hebrew: "קשה" },
  { english: "dinner", hebrew: "ארוחת ערב" },
  { english: "dirty", hebrew: "מלוכלך" },
  { english: "do", hebrew: "לעשות" },
  { english: "doctor", hebrew: "רופא" },
  { english: "dog", hebrew: "כלב" },
  { english: "doll", hebrew: "בובה" },
  { english: "don't / do not", hebrew: "אל למשל: אל תלך! (!Don't go)" },
  { english: "door", hebrew: "דלת" },
  { english: "down", hebrew: "למטה" },
  { english: "draw", hebrew: "לצייר, למשוך" },
  { english: "dream", hebrew: "חלום, לחלום" },
  { english: "dress", hebrew: "שמלה, להתלבש" },
  { english: "drink", hebrew: "לשתות, משקה" },
  { english: "drive", hebrew: "לנהוג" },
  { english: "driver", hebrew: "נהג" },
  { english: "dry", hebrew: "יבש" },
  { english: "during", hebrew: "במהלך, במשך" },

  // --- E ---
  { english: "each", hebrew: "כל אחד" },
  { english: "ear", hebrew: "אוזן" },
  { english: "early", hebrew: "מוקדם" },
  { english: "earth", hebrew: "כדור הארץ, אדמה" },
  { english: "easy", hebrew: "קל" },
  { english: "eat", hebrew: "לאכול" },
  { english: "egg", hebrew: "ביצה" },
  { english: "eight", hebrew: "שמונה" },
  { english: "eighteen", hebrew: "שמונה עשרה" },
  { english: "eighty", hebrew: "שמונים" },
  { english: "eleven", hebrew: "אחת עשרה" },
  { english: "email", hebrew: "דואר אלקטרוני" },
  { english: "end / in the end", hebrew: "סוף / בסופו של דבר" },
  { english: "engine", hebrew: "מנוע" },
  { english: "English", hebrew: "אנגלית" },
  { english: "enjoy", hebrew: "ליהנות" },
  { english: "enough", hebrew: "מספיק" },
  { english: "enter", hebrew: "להיכנס" },
  { english: "envelope", hebrew: "מעטפה" },
  { english: "evening", hebrew: "ערב" },
  { english: "every", hebrew: "כל" },
  { english: "everybody / everyone", hebrew: "כולם" },
  { english: "everything", hebrew: "הכל" },
  { english: "everywhere", hebrew: "בכל מקום" },
  { english: "example", hebrew: "דוגמה" },
  { english: "excuse me", hebrew: "סלח לי" },
  { english: "exercise", hebrew: "תרגיל, להתעמל" },
  { english: "expensive", hebrew: "יקר" },
  { english: "eye", hebrew: "עין" },

  // --- F ---
  { english: "face", hebrew: "פנים" },
  { english: "fact / in fact", hebrew: "עובדה / למעשה" },
  { english: "fair", hebrew: "הוגן, יריד" },
  { english: "fall", hebrew: "ליפול, סתיו" },
  { english: "family", hebrew: "משפחה" },
  { english: "famous", hebrew: "מפורסם" },
  { english: "far", hebrew: "רחוק" },
  { english: "farm", hebrew: "חווה" },
  { english: "fast", hebrew: "מהיר, מהר" },
  { english: "fat", hebrew: "שמן" },
  { english: "father", hebrew: "אבא" },
  { english: "favorite", hebrew: "מועדף" },
  { english: "feel", hebrew: "להרגיש" },
  { english: "few / a few", hebrew: "מעט / אחדים, כמה" },
  { english: "fifteen", hebrew: "חמש עשרה" },
  { english: "fifty", hebrew: "חמישים" },
  { english: "fight", hebrew: "להילחם, לריב" },
  { english: "film", hebrew: "סרט" },
  { english: "find", hebrew: "למצוא" },
  { english: "find out", hebrew: "לגלות" },
  { english: "fine", hebrew: "בסדר, טוב, קנס" },
  { english: "finish", hebrew: "לסיים" },
  { english: "fire", hebrew: "אש, שריפה" },
  { english: "first", hebrew: "ראשון" },
  { english: "fish", hebrew: "דג, לדוג" },
  { english: "five", hebrew: "חמש" },
  { english: "floor", hebrew: "רצפה, קומה" },
  { english: "flower", hebrew: "פרח" },
  { english: "fly", hebrew: "לטוס, לעוף, זבוב" },
  { english: "food", hebrew: "אוכל" },
  { english: "foot / feet", hebrew: "כף רגל / כפות רגליים" },
  { english: "for", hebrew: "בשביל, עבור" },
  { english: "foreign", hebrew: "זר, חיצוני" },
  { english: "forget", hebrew: "לשכוח" },
  { english: "fork", hebrew: "מזלג" },
  { english: "four", hebrew: "ארבע" },
  { english: "fourteen", hebrew: "ארבע עשרה" },
  { english: "forty", hebrew: "ארבעים" },
  { english: "free", hebrew: "חופשי, חינם" },
  { english: "fresh", hebrew: "טרי, רענן" },
  { english: "Friday", hebrew: "יום שישי" },
  { english: "friend", hebrew: "חבר" },
  { english: "frightened", hebrew: "מבוהל, מפוחד" },
  { english: "from", hebrew: "מ..., מן" },
  { english: "front / in front of", hebrew: "חזית / לפני, מול" },
  { english: "fruit", hebrew: "פירות" },
  { english: "full", hebrew: "מלא" },
  { english: "fun", hebrew: "כיף" },
  { english: "funny", hebrew: "מצחיק" },
  { english: "future", hebrew: "עתיד" },

  // --- G ---
  { english: "game", hebrew: "משחק" },
  { english: "garden", hebrew: "גינה, גן" },
  { english: "gate", hebrew: "שער" },
  { english: "gentleman", hebrew: "אדון" },
  { english: "get", hebrew: "לקבל, להשיג" },
  { english: "get up", hebrew: "לקום" },
  { english: "girl", hebrew: "ילדה" },
  { english: "give", hebrew: "לתת" },
  { english: "glad", hebrew: "שמח" },
  { english: "glass", hebrew: "זכוכית, כוס" },
  { english: "go", hebrew: "ללכת" },
  { english: "go back", hebrew: "לחזור" },
  { english: "go on", hebrew: "להמשיך" },
  { english: "god", hebrew: "אלוהים" },
  { english: "gold", hebrew: "זהב" },
  { english: "good", hebrew: "טוב" },
  { english: "goodbye / bye", hebrew: "להתראות" },
  { english: "grandma / grandmother", hebrew: "סבתא" },
  { english: "grandpa / grandfather", hebrew: "סבא" },
  { english: "grass", hebrew: "דשא" },
  { english: "great", hebrew: "נהדר, גדול" },
  { english: "green", hebrew: "ירוק" },
  { english: "ground", hebrew: "אדמה, קרקע" },
  { english: "group", hebrew: "קבוצה" },
  { english: "grow", hebrew: "לגדול, לגדל" },
  { english: "guess", hebrew: "לנחש" },
  { english: "guest", hebrew: "אורח" },
  { english: "guide", hebrew: "מדריך, להדריך" },
  { english: "guitar", hebrew: "גיטרה" },
  { english: "guy", hebrew: "בחור" },

  // --- H ---
  { english: "hair", hebrew: "שיער" },
  { english: "half", hebrew: "חצי" },
  { english: "hand", hebrew: "יד" },
  { english: "happen", hebrew: "לקרות" },
  { english: "happy", hebrew: "שמח" },
  { english: "hard", hebrew: "קשה, קשיח" },
  { english: "hat", hebrew: "כובע" },
  { english: "hate", hebrew: "לשנוא" },
  { english: "have / has", hebrew: "יש ל..." },
  { english: "have to", hebrew: "חייב" },
  { english: "he", hebrew: "הוא" },
  { english: "head", hebrew: "ראש" },
  { english: "healthy", hebrew: "בריא" },
  { english: "hear", hebrew: "לשמוע" },
  { english: "heart", hebrew: "לב" },
  { english: "heavy", hebrew: "כבד" },
  { english: "hello", hebrew: "שלום" },
  { english: "help", hebrew: "לעזור, עזרה" },
  { english: "her", hebrew: "אותה, שלה" },
  { english: "here", hebrew: "כאן, פה" },
  { english: "high", hebrew: "גבוה" },
  { english: "hill", hebrew: "גבעה" },
  { english: "him", hebrew: "אותו" },
  { english: "his", hebrew: "שלו" },
  { english: "history", hebrew: "היסטוריה" },
  { english: "hit", hebrew: "להכות, לפגוע" },
  { english: "hobby", hebrew: "תחביב" },
  { english: "hold", hebrew: "להחזיק" },
  { english: "hole", hebrew: "חור" },
  { english: "holiday", hebrew: "חג, חופשה" },
  { english: "home", hebrew: "בית" },
  { english: "hope", hebrew: "לקוות, תקווה" },
  { english: "horse", hebrew: "סוס" },
  { english: "hospital", hebrew: "בית חולים" },
  { english: "hot", hebrew: "חם" },
  { english: "hotel", hebrew: "בית מלון" },
  { english: "hour", hebrew: "שעה" },
  { english: "house", hebrew: "בית" },
  { english: "how", hebrew: "איך, כיצד" },
  { english: "hundred", hebrew: "מאה" },
  { english: "hungry", hebrew: "רעב" },
  { english: "hurry", hebrew: "למהר" },
  { english: "hurt", hebrew: "לפגוע, לכאוב" },
  { english: "husband", hebrew: "בעל" },

  // --- I / J / K ---
  { english: "I", hebrew: "אני" },
  { english: "ice", hebrew: "קרח" },
  { english: "ice cream", hebrew: "גלידה" },
  { english: "idea", hebrew: "רעיון" },
  { english: "if", hebrew: "אם" },
  { english: "ill", hebrew: "חולה" },
  { english: "important", hebrew: "חשוב" },
  { english: "in", hebrew: "בתוך, ב..." },
  { english: "inside", hebrew: "בפנים" },
  { english: "interested", hebrew: "מעוניין" },
  { english: "interesting", hebrew: "מעניין" },
  { english: "into", hebrew: "לתוך" },
  { english: "invite", hebrew: "להזמין" },
  { english: "is", hebrew: "הוא/היא נמצא (פועל עזר)" },
  { english: "it", hebrew: "זה (עבור חפץ או חיה)" },
  { english: "jacket", hebrew: "ג'קט, ז'קט" },
  { english: "job", hebrew: "עבודה, משרה" },
  { english: "join", hebrew: "להצטרף" },
  { english: "joke", hebrew: "בדיחה" },
  { english: "juice", hebrew: "מיץ" },
  { english: "jump", hebrew: "לקפוץ" },
  { english: "just", hebrew: "רק, בדיוק" },
  { english: "keep", hebrew: "לשמור" },
  { english: "key", hebrew: "מפתח" },
  { english: "kick", hebrew: "לבעוט" },
  { english: "kid", hebrew: "ילד" },
  { english: "kind", hebrew: "אדיב, סוג" },
  { english: "king", hebrew: "מלך" },
  { english: "kitchen", hebrew: "מטבח" },
  { english: "knee", hebrew: "ברך" },
  { english: "knife", hebrew: "סכין" },
  { english: "know", hebrew: "לדעת, להכיר" },

  // --- L ---
  { english: "lake", hebrew: "אגם" },
  { english: "lamp", hebrew: "מנורה" },
  { english: "land", hebrew: "אדמה, לנחות" },
  { english: "language", hebrew: "שפה" },
  { english: "large", hebrew: "גדול, רחב" },
  { english: "last", hebrew: "אחרון" },
  { english: "late", hebrew: "מאוחר" },
  { english: "laugh", hebrew: "לצחוק" },
  { english: "learn", hebrew: "ללמוד" },
  { english: "least / at least", hebrew: "הכי פחות / לפחות" },
  { english: "leave", hebrew: "לעזוב" },
  { english: "left", hebrew: "שמאל, שמאלה" },
  { english: "leg", hebrew: "רגל" },
  { english: "lesson", hebrew: "שיעור" },
  { english: "let", hebrew: "להרשות, לתת" },
  { english: "let's", hebrew: "בואו נ..." },
  { english: "letter", hebrew: "מכתב, אות" },
  { english: "library", hebrew: "ספרייה" },
  { english: "lie", hebrew: "לשקר, לשכב" },
  { english: "life", hebrew: "חיים" },
  { english: "light", hebrew: "אור, קל" },
  { english: "like", hebrew: "לאהוב, כמו" },
  { english: "line", hebrew: "שורה, קו" },
  { english: "lion", hebrew: "אריה" },
  { english: "listen", hebrew: "להקשיב" },
  { english: "little / a little", hebrew: "קטן / קצת" },
  { english: "live", hebrew: "לחיות, לגור" },
  { english: "long", hebrew: "ארוך" },
  { english: "look", hebrew: "להביט, להסתכל" },
  { english: "lose", hebrew: "לאבד, להפסיד" },
  { english: "lost", hebrew: "אבוד" },
  { english: "lot / a lot of", hebrew: "הרבה / הרבה מ..." },
  { english: "love", hebrew: "אהבה, לאהוב" },
  { english: "low", hebrew: "נמוך" },
  { english: "lunch", hebrew: "ארוחת צהריים" },

  // --- M ---
  { english: "make", hebrew: "לעשות, לייצר" },
  { english: "man / men", hebrew: "איש / אנשים" },
  { english: "many", hebrew: "הרבה" },
  { english: "map", hebrew: "מפה" },
  { english: "market", hebrew: "שוק" },
  { english: "marry", hebrew: "להתחתן" },
  { english: "match", hebrew: "להתאים, גפרור, משחק" },
  { english: "matter", hebrew: "עניין, משמעות" },
  { english: "maybe", hebrew: "אולי" },
  { english: "me", hebrew: "אותי, לי" },
  { english: "meal", hebrew: "ארוחה" },
  { english: "mean", hebrew: "להתכוון, קמצן" },
  { english: "meat", hebrew: "בשר" },
  { english: "meet", hebrew: "לפגוש" },
  { english: "meeting", hebrew: "פגישה, אסיפה" },
  { english: "message", hebrew: "הודעה" },
  { english: "middle", hebrew: "אמצע" },
  { english: "milk", hebrew: "חלב" },
  { english: "million", hebrew: "מיליון" },
  { english: "mind", hebrew: "דעת, ראש, לשים לב" },
  { english: "minute", hebrew: "דקה" },
  { english: "mirror", hebrew: "מראה" },
  { english: "miss", hebrew: "להתגעגע, לפספס" },
  { english: "mistake", hebrew: "טעות" },
  { english: "mix", hebrew: "לערבב" },
  { english: "model", hebrew: "דגם, מודל" },
  { english: "mom / mum", hebrew: "אמא" },
  { english: "moment / at the moment", hebrew: "רגע / כרגע" },
  { english: "Monday", hebrew: "יום שני" },
  { english: "money", hebrew: "כסף" },
  { english: "monkey", hebrew: "קוף" },
  { english: "month", hebrew: "חודש" },
  { english: "moon", hebrew: "ירח" },
  { english: "more", hebrew: "עוד, יותר" },
  { english: "morning", hebrew: "בוקר" },
  { english: "most", hebrew: "הכי, רוב" },
  { english: "mother", hebrew: "אמא" },
  { english: "mountain", hebrew: "הר" },
  { english: "mouth", hebrew: "פה" },
  { english: "move", hebrew: "לזוז, לעבור דירה" },
  { english: "movie", hebrew: "סרט" },
  { english: "much", hebrew: "הרבה (עבור שמות עצם בלתי ספירים)" },
  { english: "music", hebrew: "מוזיקה" },
  { english: "must", hebrew: "חייב" },
  { english: "my", hebrew: "שלי" },
  { english: "myself", hebrew: "עצמי" },

  // --- N ---
  { english: "name", hebrew: "שם" },
  { english: "nature", hebrew: "טבע" },
  { english: "near", hebrew: "קרוב" },
  { english: "necessary", hebrew: "נחוץ, חיוני" },
  { english: "neck", hebrew: "צוואר" },
  { english: "need", hebrew: "להצטרך, צורך" },
  { english: "neighbor", hebrew: "שכן" },
  { english: "never", hebrew: "אף פעם, מעולם לא" },
  { english: "new", hebrew: "חדש" },
  { english: "news", hebrew: "חדשות" },
  { english: "newspaper", hebrew: "עיתון" },
  { english: "next / next to", hebrew: "הבא / ליד" },
  { english: "nice", hebrew: "נחמד" },
  { english: "night / at night", hebrew: "לילה / בלילה" },
  { english: "nine", hebrew: "תשע" },
  { english: "nineteen", hebrew: "תשע עשרה" },
  { english: "ninety", hebrew: "תשעים" },
  { english: "no", hebrew: "לא" },
  { english: "nobody / no-one", hebrew: "אף אחד" },
  { english: "noise", hebrew: "רעש" },
  { english: "north", hebrew: "צפון" },
  { english: "nose", hebrew: "אף" },
  { english: "not", hebrew: "לא (מילת שלילה)" },
  { english: "notebook", hebrew: "מחברת" },
  { english: "nothing", hebrew: "כלום, שום דבר" },
  { english: "now", hebrew: "עכשיו" },
  { english: "number", hebrew: "מספר" },
  { english: "nurse", hebrew: "אח/אחות רפואית" },

  // --- O ---
  { english: "ocean", hebrew: "אוקיינוס" },
  { english: "o'clock", hebrew: "השעה... (בדיוק)" },
  { english: "of", hebrew: "של" },
  { english: "off", hebrew: "כבוי, מחוץ ל..." },
  { english: "office", hebrew: "משרד" },
  { english: "often", hebrew: "לעיתים קרובות" },
  { english: "oil", hebrew: "שמן" },
  { english: "OK / okay", hebrew: "בסדר" },
  { english: "old", hebrew: "ישן, זקן" },
  { english: "on", hebrew: "על" },
  { english: "once / once upon a time", hebrew: "פעם אחת / היה היה פעם" },
  { english: "one", hebrew: "אחד" },
  { english: "only", hebrew: "רק" },
  { english: "open", hebrew: "לפתוח, פתוח" },
  { english: "or", hebrew: "או" },
  { english: "orange", hebrew: "כתום, תפוז" },
  { english: "order", hebrew: "להזמין, סדר" },
  { english: "other", hebrew: "אחר" },
  { english: "our", hebrew: "שלנו" },
  { english: "ourselves", hebrew: "עצמנו" },
  { english: "out / out of", hebrew: "החוצה / מחוץ ל..." },
  { english: "outside", hebrew: "בחוץ" },
  { english: "over", hebrew: "מעל, מעבר, נגמר" },
  { english: "own", hebrew: "שלי בעצמי, של עצמו" },

  // --- P / Q ---
  { english: "page", hebrew: "עמוד, דף" },
  { english: "paint", hebrew: "לצבוע, צבע" },
  { english: "pair", hebrew: "זוג" },
  { english: "paper", hebrew: "נייר, עיתון" },
  { english: "pardon", hebrew: "סליחה?" },
  { english: "parent", hebrew: "הורה" },
  { english: "park", hebrew: "פארק, לחנות" },
  { english: "part", hebrew: "חלק" },
  { english: "partner", hebrew: "שותף" },
  { english: "party", hebrew: "מסיבה, מפלגה" },
  { english: "pass", hebrew: "לעבור, להעביר" },
  { english: "passenger", hebrew: "נוסע" },
  { english: "past", hebrew: "עבר" },
  { english: "pay", hebrew: "לשלם" },
  { english: "pen", hebrew: "עט" },
  { english: "pencil", hebrew: "עיפרון" },
  { english: "people", hebrew: "אנשים" },
  { english: "person", hebrew: "בן אדם" },
  { english: "pet", hebrew: "חיית מחמד" },
  { english: "phone / telephone", hebrew: "טלפון" },
  { english: "photo / photograph", hebrew: "תמונה, תצלום" },
  { english: "piano", hebrew: "פסנתר" },
  { english: "picture", hebrew: "תמונה" },
  { english: "piece", hebrew: "חתיכה, חלק" },
  { english: "pig", hebrew: "חזיר" },
  { english: "pilot", hebrew: "טייס" },
  { english: "pink", hebrew: "ורוד" },
  { english: "pizza", hebrew: "פיצה" },
  { english: "place", hebrew: "מקום" },
  { english: "plan", hebrew: "תוכנית, לתכנן" },
  { english: "plane", hebrew: "מטוס" },
  { english: "plant", hebrew: "צמח, לשתול, מפעל" },
  { english: "play", hebrew: "לשחק, לנגן, מחזה" },
  { english: "player", hebrew: "שחקן (בספורט או משחק)" },
  { english: "playground", hebrew: "מגרש משחקים" },
  { english: "please", hebrew: "בבקשה" },
  { english: "pocket", hebrew: "כיס" },
  { english: "point", hebrew: "נקודה, להצביע" },
  { english: "police", hebrew: "משטרה" },
  { english: "policeman", hebrew: "שוטר" },
  { english: "pool", hebrew: "בריכה" },
  { english: "poor", hebrew: "עני, מסכן" },
  { english: "popular", hebrew: "פופולרי, אהוד" },
  { english: "post office", hebrew: "בית דואר" },
  { english: "potato", hebrew: "תפוח אדמה" },
  { english: "prepare", hebrew: "להכין" },
  { english: "present", hebrew: "מתנה, הווה, נוכח" },
  { english: "pretty", hebrew: "יפה, די (למשל: די גדול)" },
  { english: "price", hebrew: "מחיר" },
  { english: "problem", hebrew: "בעיה" },
  { english: "pupil", hebrew: "תלמיד, אישון העין" },
  { english: "purple", hebrew: "סגול" },
  { english: "push", hebrew: "לדחוף" },
  { english: "put", hebrew: "לשים" },
  { english: "quarter", hebrew: "רבע" },
  { english: "queen", hebrew: "מלכה" },
  { english: "question", hebrew: "שאלה" },
  { english: "quick / quickly", hebrew: "מהיר / במהירות" },
  { english: "quiet", hebrew: "שקט" },

  // --- R ---
  { english: "radio", hebrew: "רדיו" },
  { english: "rain", hebrew: "גשם" },
  { english: "read", hebrew: "לקרוא" },
  { english: "ready", hebrew: "מוכן" },
  { english: "real", hebrew: "אמיתי" },
  { english: "red", hebrew: "אדום" },
  { english: "remember", hebrew: "לזכור" },
  { english: "rest", hebrew: "לנוח, מנוחה, שאר ה..." },
  { english: "restaurant", hebrew: "מסעדה" },
  { english: "return", hebrew: "לחזור, להחזיר" },
  { english: "rice", hebrew: "אורז" },
  { english: "rich", hebrew: "עשיר" },
  { english: "ride", hebrew: "לרכוב, נסיעה" },
  { english: "right", hebrew: "ימין, נכון, צודק" },
  { english: "right now", hebrew: "ממש עכשיו" },
  { english: "river", hebrew: "נהר" },
  { english: "road", hebrew: "כביש, דרך" },
  { english: "room", hebrew: "חדר, מקום, מרווח" },
  { english: "round", hebrew: "עגול" },
  { english: "rule", hebrew: "חוק, כלל" },
  { english: "run", hebrew: "לרוץ" },
  { english: "runner", hebrew: "רץ" },

  // --- S ---
  { english: "sad", hebrew: "עצוב" },
  { english: "safe", hebrew: "בטוח, כספת" },
  { english: "salad", hebrew: "סלט" },
  { english: "salt", hebrew: "מלח" },
  { english: "same", hebrew: "אותו הדבר" },
  { english: "sandwich", hebrew: "כריך, סנדוויץ'" },
  { english: "Saturday", hebrew: "יום שבת" },
  { english: "save", hebrew: "להציל, לשמור, לחסוך" },
  { english: "say", hebrew: "לומר" },
  { english: "school", hebrew: "בית ספר" },
  { english: "sea", hebrew: "ים" },
  { english: "season", hebrew: "עונה" },
  { english: "seat", hebrew: "מושב, מקום ישיבה" },
  { english: "second", hebrew: "שני (בסדר), שנייה (זמן)" },
  { english: "secret", hebrew: "סוד" },
  { english: "see", hebrew: "לראות" },
  { english: "sell", hebrew: "למכור" },
  { english: "send", hebrew: "לשלוח" },
  { english: "sentence", hebrew: "משפט" },
  { english: "September", hebrew: "ספטמבר" },
  { english: "seven", hebrew: "שבע" },
  { english: "seventeen", hebrew: "שבע עשרה" },
  { english: "seventy", hebrew: "שבעים" },
  { english: "share", hebrew: "לשתף, לחלוק" },
  { english: "sharp", hebrew: "חד" },
  { english: "she", hebrew: "היא" },
  { english: "sheep", hebrew: "כבשה, כבשים" },
  { english: "shirt", hebrew: "חולצה" },
  { english: "shoe", hebrew: "נעל" },
  { english: "shop / store", hebrew: "חנות, לקנות" },
  { english: "short", hebrew: "קצר, נמוך" },
  { english: "shout", hebrew: "לצעוק" },
  { english: "show", hebrew: "להראות, תוכנית, הופעה" },
  { english: "shut", hebrew: "לסגור, סגור" },
  { english: "sick", hebrew: "חולה" },
  { english: "side", hebrew: "צד" },
  { english: "sign", hebrew: "שלט, סימן, לחתום" },
  { english: "silent", hebrew: "שקט" },
  { english: "silver", hebrew: "כסף (מתכת או צבע)" },
  { english: "simple", hebrew: "פשוט" },
  { english: "since", hebrew: "מאז, מכיוון ש..." },
  { english: "sing", hebrew: "לשיר" },
  { english: "singer", hebrew: "זמר" },
  { english: "sister", hebrew: "אחות" },
  { english: "sit", hebrew: "לשבת" },
  { english: "six", hebrew: "שש" },
  { english: "sixteen", hebrew: "שש עשרה" },
  { english: "sixty", hebrew: "שישים" },
  { english: "size", hebrew: "מידה, גודל" },
  { english: "sky", hebrew: "שמיים" },
  { english: "sleep", hebrew: "לישון, שינה" },
  { english: "slow / slowly", hebrew: "איטי / לאט" },
  { english: "small", hebrew: "קטן" },
  { english: "smart", hebrew: "חכם, אלגנטי" },
  { english: "smell", hebrew: "להריח, ריח" },
  { english: "smile", hebrew: "לחייך, חיוך" },
  { english: "smoke", hebrew: "לעשן, עשן" },
  { english: "snow", hebrew: "שלג" },
  { english: "so", hebrew: "כל כך, לכן" },
  { english: "soap", hebrew: "סבון" },
  { english: "sock", hebrew: "גרב" },
  { english: "sofa", hebrew: "ספה" },
  { english: "some", hebrew: "כמה, חלק מ..." },
  { english: "somebody / someone", hebrew: "מישהו" },
  { english: "something", hebrew: "משהו" },
  { english: "sometimes", hebrew: "לפעמים" },
  { english: "son", hebrew: "בן" },
  { english: "song", hebrew: "שיר" },
  { english: "soon", hebrew: "בקרוב" },
  { english: "sorry", hebrew: "מצטער" },
  { english: "sound", hebrew: "צליל, קול, נשמע" },
  { english: "soup", hebrew: "מרק" },
  { english: "south", hebrew: "דרום" },
  { english: "space", hebrew: "חלל, מרווח" },
  { english: "speak", hebrew: "לדבר" },
  { english: "special", hebrew: "מיוחד" },
  { english: "spell", hebrew: "לאיית" },
  { english: "spend", hebrew: "לבזבז כסף, לבלות זמן" },
  { english: "spoon", hebrew: "כף" },
  { english: "sport", hebrew: "ספורט" },
  { english: "spring", hebrew: "אביב, קפיץ" },
  { english: "square", hebrew: "ריבוע, כיכר עיר" },
  { english: "stairs", hebrew: "מדרגות" },
  { english: "stand", hebrew: "לעמוד" },
  { english: "star", hebrew: "כוכב" },
  { english: "start", hebrew: "להתחיל" },
  { english: "station", hebrew: "תחנה" },
  { english: "stay", hebrew: "להישאר" },
  { english: "still", hebrew: "עדיין" },
  { english: "stone", hebrew: "אבן" },
  { english: "stop", hebrew: "לעצור, תחנה" },
  { english: "story", hebrew: "סיפור" },
  { english: "straight", hebrew: "ישר" },
  { english: "strange", hebrew: "מוזר" },
  { english: "street", hebrew: "רחוב" },
  { english: "strong", hebrew: "חזק" },
  { english: "student", hebrew: "סטודנט, תלמיד" },
  { english: "study", hebrew: "ללמוד, לחקור" },
  { english: "stupid", hebrew: "טיפש" },
  { english: "suddenly", hebrew: "פתאום" },
  { english: "sugar", hebrew: "סוכר" },
  { english: "suit", hebrew: "חליפה, להתאים" },
  { english: "summer", hebrew: "קיץ" },
  { english: "sun", hebrew: "שמש" },
  { english: "Sunday", hebrew: "יום ראשון" },
  { english: "supper", hebrew: "ארוחת ערב קלה" },
  { english: "sure", hebrew: "בטוח" },
  { english: "surprise", hebrew: "הפתעה, להפתיע" },
  { english: "sweet", hebrew: "מתוק" },
  { english: "swim", hebrew: "לשחות" },

  // --- T ---
  { english: "table", hebrew: "שולחן" },
  { english: "take", hebrew: "לקחת" },
  { english: "take care", hebrew: "להישמר, לטפל ב..." },
  { english: "talk", hebrew: "לדבר" },
  { english: "tall", hebrew: "גבוה" },
  { english: "tea", hebrew: "תה" },
  { english: "teach", hebrew: "ללמד" },
  { english: "teacher", hebrew: "מורה" },
  { english: "team", hebrew: "קבוצה, צוות" },
  { english: "tear", hebrew: "דמעה, לקרוע" },
  { english: "telephone", hebrew: "טלפון" },
  { english: "television / TV", hebrew: "טלוויזיה" },
  { english: "tell", hebrew: "לספר, להגיד" },
  { english: "ten", hebrew: "עשר" },
  { english: "test", hebrew: "מבחן, לבחון" },
  { english: "than", hebrew: "מאשר (בהשוואה)" },
  { english: "thank you / thanks", hebrew: "תודה" },
  { english: "that", hebrew: "ההוא, ש..." },
  { english: "the", hebrew: "ה' הידיעה" },
  { english: "their", hebrew: "שלהם" },
  { english: "them", hebrew: "אותם" },
  { english: "themselves", hebrew: "עצמם" },
  { english: "then", hebrew: "אז, לאחר מכן" },
  { english: "there", hebrew: "שם" },
  { english: "these", hebrew: "אלה" },
  { english: "they", hebrew: "הם" },
  { english: "thick", hebrew: "עבה" },
  { english: "thin", hebrew: "רזה, דק" },
  { english: "thing", hebrew: "דבר, חפץ" },
  { english: "think", hebrew: "לחשוב" },
  { english: "third", hebrew: "שלישי" },
  { english: "thirsty", hebrew: "צמא" },
  { english: "thirteen", hebrew: "שלוש עשרה" },
  { english: "thirty", hebrew: "שלושים" },
  { english: "this", hebrew: "הזה, הזאת" },
  { english: "those", hebrew: "ההם" },
  { english: "thousand", hebrew: "אלף" },
  { english: "three", hebrew: "שלוש" },
  { english: "through", hebrew: "דרך, מבעד ל..." },
  { english: "throw", hebrew: "לזרוק" },
  { english: "Thursday", hebrew: "יום חמישי" },
  { english: "ticket", hebrew: "כרטיס" },
  { english: "tidy", hebrew: "מסודר" },
  { english: "tie", hebrew: "עניבה, לקשור" },
  { english: "tiger", hebrew: "נמר" },
  { english: "time", hebrew: "זמן, פעם" },
  { english: "tired", hebrew: "עייף" },
  { english: "to", hebrew: "אל, ל..." },
  { english: "today", hebrew: "היום" },
  { english: "toe", hebrew: "אצבע בכף הרגל" },
  { english: "together", hebrew: "ביחד" },
  { english: "tomato", hebrew: "עגבנייה" },
  { english: "tomorrow", hebrew: "מחר" },
  { english: "tongue", hebrew: "לשון" },
  { english: "tonight", hebrew: "הלילה" },
  { english: "too", hebrew: "גם, יותר מדי" },
  { english: "tooth / teeth", hebrew: "שן / שיניים" },
  { english: "top", hebrew: "פסגה, עליון" },
  { english: "touch", hebrew: "לגעת, מגע" },
  { english: "towel", hebrew: "מגבת" },
  { english: "tower", hebrew: "מגדל" },
  { english: "town", hebrew: "עיר קטנה, עיירה" },
  { english: "toy", hebrew: "צעצוע" },
  { english: "train", hebrew: "רכבת, לאמן" },
  { english: "travel", hebrew: "לנסוע, לטייל" },
  { english: "tree", hebrew: "עץ" },
  { english: "trip", hebrew: "טיול" },
  { english: "trouble", hebrew: "צרה, בעיה" },
  { english: "trousers", hebrew: "מכנסיים" },
  { english: "true", hebrew: "נכון, אמיתי" },
  { english: "truth", hebrew: "אמת" },
  { english: "try", hebrew: "לנסות" },
  { english: "T-shirt", hebrew: "חולצת טי" },
  { english: "Tuesday", hebrew: "יום שלישי" },
  { english: "turn", hebrew: "להסתובב, לפנות, תור" },
  { english: "turn off", hebrew: "לכבות" },
  { english: "turn on", hebrew: "להדליק" },
  { english: "twelve", hebrew: "שתים עשרה" },
  { english: "twenty", hebrew: "עשרים" },
  { english: "twice", hebrew: "פעמיים" },
  { english: "two", hebrew: "שתיים" },
  { english: "type", hebrew: "סוג, להקליד" },

  // --- U / V / W / Y / Z ---
  { english: "ugly", hebrew: "מכוער" },
  { english: "uncle", hebrew: "דוד" },
  { english: "under", hebrew: "תחת, מתחת ל..." },
  { english: "understand", hebrew: "להבין" },
  { english: "uniform", hebrew: "מדים" },
  { english: "university", hebrew: "אוניברסיטה" },
  { english: "until", hebrew: "עד ש..." },
  { english: "up", hebrew: "למעלה" },
  { english: "upon", hebrew: "על, מעל" },
  { english: "us", hebrew: "אותנו, לנו" },
  { english: "use", hebrew: "להשתמש, שימוש" },
  { english: "useful", hebrew: "שימושי" },
  { english: "usual / usually", hebrew: "רגיל / בדרך כלל" },
  { english: "vacation", hebrew: "חופשה" },
  { english: "vegetable", hebrew: "ירק" },
  { english: "very", hebrew: "מאוד" },
  { english: "video", hebrew: "וידאו" },
  { english: "view", hebrew: "נוף, נקודת מבט" },
  { english: "visit", hebrew: "לבקר, ביקור" },
  { english: "voice", hebrew: "קול" },
  { english: "wait", hebrew: "לחכות" },
  { english: "waiter", hebrew: "מלצר" },
  { english: "wake up", hebrew: "להתעורר" },
  { english: "walk", hebrew: "ללכת, הליכה" },
  { english: "wall", hebrew: "קיר, חומה" },
  { english: "want", hebrew: "לרצות" },
  { english: "war", hebrew: "מלחמה" },
  { english: "warm", hebrew: "חם, חמים" },
  { english: "wash", hebrew: "לשטוף, לרחוץ" },
  { english: "watch", hebrew: "לצפות, שעון יד" },
  { english: "water", hebrew: "מים, להשקות" },
  { english: "wave", hebrew: "גל, לנפנף לשלום" },
  { english: "way", hebrew: "דרך, אופן" },
  { english: "we", hebrew: "אנחנו" },
  { english: "wear", hebrew: "ללבוש, לעטות" },
  { english: "weather", hebrew: "מזג אוויר" },
  { english: "website", hebrew: "אתר אינטרנט" },
  { english: "Wednesday", hebrew: "יום רביעי" },
  { english: "week", hebrew: "שבוע" },
  { english: "weekend", hebrew: "סוף שבוע" },
  { english: "welcome", hebrew: "ברוך הבא" },
  { english: "well", hebrew: "היטב, טוב, באר" },
  { english: "west", hebrew: "מערב" },
  { english: "wet", hebrew: "רטוב" },
  { english: "what", hebrew: "מה" },
  { english: "when", hebrew: "מתי, כאשר" },
  { english: "where", hebrew: "איפה, היכן" },
  { english: "which", hebrew: "איזה, אשר" },
  { english: "while", hebrew: "בזמן ש..., בעוד" },
  { english: "white", hebrew: "לבן" },
  { english: "who", hebrew: "מי, ש..." },
  { english: "whole", hebrew: "שלם, כל ה..." },
  { english: "whose", hebrew: "של מי" },
  { english: "why", hebrew: "למה, מדוע" },
  { english: "wide", hebrew: "רחב" },
  { english: "wife", hebrew: "אישה (נשואה)" },
  { english: "wild", hebrew: "פראי, בר" },
  { english: "will", hebrew: "יקרה בעתיד (פועל עזר), רצון, צוואה" },
  { english: "win", hebrew: "לנצח, לזכות" },
  { english: "wind", hebrew: "רוח" },
  { english: "window", hebrew: "חלון" },
  { english: "wine", hebrew: "יין" },
  { english: "winter", hebrew: "חורף" },
  { english: "wise", hebrew: "חכם" },
  { english: "wish", hebrew: "לרצות, משאלה" },
  { english: "with", hebrew: "עם" },
  { english: "without", hebrew: "בלי, ללא" },
  { english: "woman / women", hebrew: "אישה / נשים" },
  { english: "wonderful", hebrew: "נפלא" },
  { english: "word", hebrew: "מילה" },
  { english: "work", hebrew: "לעבוד, עבודה" },
  { english: "worker", hebrew: "עובד" },
  { english: "world", hebrew: "עולם" },
  { english: "worry", hebrew: "לדאוג, דאגה" },
  { english: "worse", hebrew: "גרוע יותר" },
  { english: "worst", hebrew: "הגרוע ביותר" },
  { english: "write", hebrew: "לכתוב" },
  { english: "writer", hebrew: "כותב, סופר" },
  { english: "wrong", hebrew: "לא נכון, מוטעה" },
  { english: "yard", hebrew: "חצר" },
  { english: "year", hebrew: "שנה" },
  { english: "yellow", hebrew: "צהוב" },
  { english: "yes", hebrew: "כן" },
  { english: "yesterday", hebrew: "אתמול" },
  { english: "yet", hebrew: "עדיין, כבר (במשפטי שלילה ושאלה)" },
  { english: "you", hebrew: "אתה, את, אתם, אתכן" },
  { english: "young", hebrew: "צעיר" },
  { english: "your", hebrew: "שלך, שלכם" },
  { english: "yourself", hebrew: "עצמך" },
  { english: "zoo", hebrew: "גן חיות" }
];

// Attach the array cleanly to the global window object.
// This allows your main frontend controller (e.g., app.js) to dynamically access 
// the static lexicon items directly via window.band1Words.
window.band1Words = band1Words;
